version: '3.8'

services:
  app:
    image: cloud-storage-kukdo:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - FILE_SERVICE_TYPE=${FILE_SERVICE_TYPE} # local or aliyun
      - FILE_UPLOAD_DIR=${FILE_UPLOAD_DIR}
      - ALIYUN_OSS_ENDPOINT=${ALIYUN_OSS_ENDPOINT}
      - ALIYUN_OSS_ACCESS_KEY_ID=${ALIYUN_OSS_ACCESS_KEY_ID}
      - ALIYUN_OSS_ACCESS_KEY_SECRET=${ALIYUN_OSS_ACCESS_KEY_SECRET}
      - ALIYUN_OSS_BUCKET_NAME=${ALIYUN_OSS_BUCKET_NAME}
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/cloud_storage?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - FILE_UPLOAD_DIR=${FILE_UPLOAD_DIR}
    volumes:
      - ./upload_files:/app/upload_files
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cloud_storage
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
